# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1464, 939)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 190, 481, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(112)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(30, 520, 951, 101))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 500, 141, 16))
        self.label_3.setObjectName("label_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(320, 660, 491, 241))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 640, 141, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 20, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.contador = QtWidgets.QLabel(self.centralwidget)
        self.contador.setGeometry(QtCore.QRect(920, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.contador.setFont(font)
        self.contador.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"font: 16pt \"Yu Gothic UI Semibold\";\n"
"")
        self.contador.setAlignment(QtCore.Qt.AlignCenter)
        self.contador.setObjectName("contador")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(850, 30, 71, 16))
        self.label_6.setObjectName("label_6")
        self.estado = QtWidgets.QLabel(self.centralwidget)
        self.estado.setGeometry(QtCore.QRect(460, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.estado.setFont(font)
        self.estado.setStyleSheet("background-color: rgb(163, 163, 163);\n"
"border-radius: 40px;\n"
"")
        self.estado.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.estado.setAlignment(QtCore.Qt.AlignCenter)
        self.estado.setObjectName("estado")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_4.setGeometry(QtCore.QRect(600, 190, 341, 281))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(112)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 170, 141, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 50, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 90, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 110, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 110, 151, 16))
        self.label_10.setObjectName("label_10")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(1072, 150, 321, 641))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar_13 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_13.setProperty("value", 0)
        self.progressBar_13.setObjectName("progressBar_13")
        self.gridLayout.addWidget(self.progressBar_13, 6, 0, 1, 1)
        self.progressBar_15 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_15.setProperty("value", 0)
        self.progressBar_15.setObjectName("progressBar_15")
        self.gridLayout.addWidget(self.progressBar_15, 7, 0, 1, 1)
        self.progressBar_11 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_11.setProperty("value", 0)
        self.progressBar_11.setObjectName("progressBar_11")
        self.gridLayout.addWidget(self.progressBar_11, 5, 0, 1, 1)
        self.progressBar_14 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_14.setProperty("value", 0)
        self.progressBar_14.setObjectName("progressBar_14")
        self.gridLayout.addWidget(self.progressBar_14, 6, 1, 1, 1)
        self.progressBar_19 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_19.setProperty("value", 0)
        self.progressBar_19.setObjectName("progressBar_19")
        self.gridLayout.addWidget(self.progressBar_19, 9, 0, 1, 1)
        self.progressBar_12 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_12.setProperty("value", 0)
        self.progressBar_12.setObjectName("progressBar_12")
        self.gridLayout.addWidget(self.progressBar_12, 5, 1, 1, 1)
        self.progressBar_17 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_17.setProperty("value", 0)
        self.progressBar_17.setObjectName("progressBar_17")
        self.gridLayout.addWidget(self.progressBar_17, 8, 0, 1, 1)
        self.progressBar_16 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_16.setProperty("value", 0)
        self.progressBar_16.setObjectName("progressBar_16")
        self.gridLayout.addWidget(self.progressBar_16, 7, 1, 1, 1)
        self.progressBar_18 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_18.setProperty("value", 0)
        self.progressBar_18.setObjectName("progressBar_18")
        self.gridLayout.addWidget(self.progressBar_18, 8, 1, 1, 1)
        self.progressBar_20 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_20.setProperty("value", 0)
        self.progressBar_20.setObjectName("progressBar_20")
        self.gridLayout.addWidget(self.progressBar_20, 9, 1, 1, 1)
        self.progressBar_21 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_21.setProperty("value", 0)
        self.progressBar_21.setObjectName("progressBar_21")
        self.gridLayout.addWidget(self.progressBar_21, 10, 0, 1, 1)
        self.progressBar_22 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_22.setProperty("value", 0)
        self.progressBar_22.setObjectName("progressBar_22")
        self.gridLayout.addWidget(self.progressBar_22, 10, 1, 1, 1)
        self.progressBar_23 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_23.setProperty("value", 0)
        self.progressBar_23.setObjectName("progressBar_23")
        self.gridLayout.addWidget(self.progressBar_23, 11, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 0, 1, 1, 1)
        self.progressBar_5 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setObjectName("progressBar_5")
        self.gridLayout.addWidget(self.progressBar_5, 2, 0, 1, 1)
        self.progressBar_7 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_7.setProperty("value", 0)
        self.progressBar_7.setObjectName("progressBar_7")
        self.gridLayout.addWidget(self.progressBar_7, 3, 0, 1, 1)
        self.progressBar_9 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_9.setProperty("value", 0)
        self.progressBar_9.setObjectName("progressBar_9")
        self.gridLayout.addWidget(self.progressBar_9, 4, 0, 1, 1)
        self.progressBar_3 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout.addWidget(self.progressBar_3, 1, 0, 1, 1)
        self.progressBar_6 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_6.setProperty("value", 0)
        self.progressBar_6.setObjectName("progressBar_6")
        self.gridLayout.addWidget(self.progressBar_6, 2, 1, 1, 1)
        self.progressBar_8 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_8.setProperty("value", 0)
        self.progressBar_8.setObjectName("progressBar_8")
        self.gridLayout.addWidget(self.progressBar_8, 3, 1, 1, 1)
        self.progressBar_10 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_10.setProperty("value", 0)
        self.progressBar_10.setObjectName("progressBar_10")
        self.gridLayout.addWidget(self.progressBar_10, 4, 1, 1, 1)
        self.progressBar_4 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName("progressBar_4")
        self.gridLayout.addWidget(self.progressBar_4, 1, 1, 1, 1)
        self.progressBar_33 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_33.setProperty("value", 0)
        self.progressBar_33.setObjectName("progressBar_33")
        self.gridLayout.addWidget(self.progressBar_33, 16, 0, 1, 1)
        self.progressBar_39 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_39.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.progressBar_39.setProperty("value", 100)
        self.progressBar_39.setObjectName("progressBar_39")
        self.gridLayout.addWidget(self.progressBar_39, 19, 0, 1, 1)
        self.progressBar_37 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_37.setProperty("value", 0)
        self.progressBar_37.setObjectName("progressBar_37")
        self.gridLayout.addWidget(self.progressBar_37, 18, 0, 1, 1)
        self.progressBar_24 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_24.setProperty("value", 0)
        self.progressBar_24.setObjectName("progressBar_24")
        self.gridLayout.addWidget(self.progressBar_24, 11, 1, 1, 1)
        self.progressBar_28 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_28.setProperty("value", 0)
        self.progressBar_28.setObjectName("progressBar_28")
        self.gridLayout.addWidget(self.progressBar_28, 13, 1, 1, 1)
        self.progressBar_26 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_26.setProperty("value", 0)
        self.progressBar_26.setObjectName("progressBar_26")
        self.gridLayout.addWidget(self.progressBar_26, 12, 1, 1, 1)
        self.progressBar_36 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_36.setProperty("value", 0)
        self.progressBar_36.setObjectName("progressBar_36")
        self.gridLayout.addWidget(self.progressBar_36, 17, 1, 1, 1)
        self.progressBar_32 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_32.setProperty("value", 0)
        self.progressBar_32.setObjectName("progressBar_32")
        self.gridLayout.addWidget(self.progressBar_32, 15, 1, 1, 1)
        self.progressBar_38 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_38.setProperty("value", 0)
        self.progressBar_38.setObjectName("progressBar_38")
        self.gridLayout.addWidget(self.progressBar_38, 18, 1, 1, 1)
        self.progressBar_40 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_40.setProperty("value", 100)
        self.progressBar_40.setObjectName("progressBar_40")
        self.gridLayout.addWidget(self.progressBar_40, 19, 1, 1, 1)
        self.progressBar_30 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_30.setProperty("value", 0)
        self.progressBar_30.setObjectName("progressBar_30")
        self.gridLayout.addWidget(self.progressBar_30, 14, 1, 1, 1)
        self.progressBar_27 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_27.setProperty("value", 0)
        self.progressBar_27.setObjectName("progressBar_27")
        self.gridLayout.addWidget(self.progressBar_27, 13, 0, 1, 1)
        self.progressBar_31 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_31.setProperty("value", 0)
        self.progressBar_31.setObjectName("progressBar_31")
        self.gridLayout.addWidget(self.progressBar_31, 15, 0, 1, 1)
        self.progressBar_25 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_25.setProperty("value", 0)
        self.progressBar_25.setObjectName("progressBar_25")
        self.gridLayout.addWidget(self.progressBar_25, 12, 0, 1, 1)
        self.progressBar_34 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_34.setProperty("value", 0)
        self.progressBar_34.setObjectName("progressBar_34")
        self.gridLayout.addWidget(self.progressBar_34, 16, 1, 1, 1)
        self.progressBar_35 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_35.setProperty("value", 0)
        self.progressBar_35.setObjectName("progressBar_35")
        self.gridLayout.addWidget(self.progressBar_35, 17, 0, 1, 1)
        self.progressBar_29 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_29.setProperty("value", 0)
        self.progressBar_29.setObjectName("progressBar_29")
        self.gridLayout.addWidget(self.progressBar_29, 14, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1070, 100, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(990, 800, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(974, 850, 71, 31))
        self.label_13.setStyleSheet("background-color: gray;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1090, 850, 81, 31))
        self.label_14.setStyleSheet("background-color: red;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1210, 850, 71, 31))
        self.label_15.setStyleSheet("background-color: DeepSkyBlue;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1320, 850, 81, 31))
        self.label_16.setStyleSheet("background-color: purple")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(680, 120, 151, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(600, 120, 71, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(600, 100, 141, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(600, 80, 131, 16))
        self.label_20.setObjectName("label_20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Paginación simple"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TT"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tamaño"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Operación"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TME"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TT"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TR"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TT Quantum"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Tamaño"))
        self.label.setText(_translate("MainWindow", "Procesos nuevos: 0"))
        self.label_2.setText(_translate("MainWindow", "Listos"))
        self.label_3.setText(_translate("MainWindow", "Proceso en ejecución"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Operación"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Resultado"))
        self.label_4.setText(_translate("MainWindow", "Terminados"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar"))
        self.contador.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Contador"))
        self.estado.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TTB"))
        self.label_5.setText(_translate("MainWindow", "Bloqueados"))
        self.label_7.setText(_translate("MainWindow", "Valor de quantum: -"))
        self.label_8.setText(_translate("MainWindow", "Siguiente nuevo"))
        self.label_9.setText(_translate("MainWindow", "ID: -"))
        self.label_10.setText(_translate("MainWindow", "Tamaño:-"))
        self.progressBar_13.setFormat(_translate("MainWindow", "12"))
        self.progressBar_15.setFormat(_translate("MainWindow", "14"))
        self.progressBar_11.setFormat(_translate("MainWindow", "10"))
        self.progressBar_14.setFormat(_translate("MainWindow", "13"))
        self.progressBar_19.setFormat(_translate("MainWindow", "18"))
        self.progressBar_12.setFormat(_translate("MainWindow", "11"))
        self.progressBar_17.setFormat(_translate("MainWindow", "16"))
        self.progressBar_16.setFormat(_translate("MainWindow", "15"))
        self.progressBar_18.setFormat(_translate("MainWindow", "17"))
        self.progressBar_20.setFormat(_translate("MainWindow", "19"))
        self.progressBar_21.setFormat(_translate("MainWindow", "20"))
        self.progressBar_22.setFormat(_translate("MainWindow", "21"))
        self.progressBar_23.setFormat(_translate("MainWindow", "22"))
        self.progressBar.setFormat(_translate("MainWindow", "0"))
        self.progressBar_2.setFormat(_translate("MainWindow", "1"))
        self.progressBar_5.setFormat(_translate("MainWindow", "4"))
        self.progressBar_7.setFormat(_translate("MainWindow", "6"))
        self.progressBar_9.setFormat(_translate("MainWindow", "8"))
        self.progressBar_3.setFormat(_translate("MainWindow", "2"))
        self.progressBar_6.setFormat(_translate("MainWindow", "5"))
        self.progressBar_8.setFormat(_translate("MainWindow", "7"))
        self.progressBar_10.setFormat(_translate("MainWindow", "9"))
        self.progressBar_4.setFormat(_translate("MainWindow", "3"))
        self.progressBar_33.setFormat(_translate("MainWindow", "32"))
        self.progressBar_39.setFormat(_translate("MainWindow", "38"))
        self.progressBar_37.setFormat(_translate("MainWindow", "36"))
        self.progressBar_24.setFormat(_translate("MainWindow", "23"))
        self.progressBar_28.setFormat(_translate("MainWindow", "27"))
        self.progressBar_26.setFormat(_translate("MainWindow", "25"))
        self.progressBar_36.setFormat(_translate("MainWindow", "35"))
        self.progressBar_32.setFormat(_translate("MainWindow", "31"))
        self.progressBar_38.setFormat(_translate("MainWindow", "37"))
        self.progressBar_40.setFormat(_translate("MainWindow", "39"))
        self.progressBar_30.setFormat(_translate("MainWindow", "29"))
        self.progressBar_27.setFormat(_translate("MainWindow", "26"))
        self.progressBar_31.setFormat(_translate("MainWindow", "30"))
        self.progressBar_25.setFormat(_translate("MainWindow", "24"))
        self.progressBar_34.setFormat(_translate("MainWindow", "33"))
        self.progressBar_35.setFormat(_translate("MainWindow", "34"))
        self.progressBar_29.setFormat(_translate("MainWindow", "28"))
        self.label_11.setText(_translate("MainWindow", "Memoria"))
        self.label_12.setText(_translate("MainWindow", "Colores"))
        self.label_13.setText(_translate("MainWindow", "SO"))
        self.label_14.setText(_translate("MainWindow", "Ejecución"))
        self.label_15.setText(_translate("MainWindow", "Listo"))
        self.label_16.setText(_translate("MainWindow", "Bloqueado"))
        self.label_17.setText(_translate("MainWindow", "Tamaño:-"))
        self.label_18.setText(_translate("MainWindow", "ID: -"))
        self.label_19.setText(_translate("MainWindow", "Siguiente suspendido"))
        self.label_20.setText(_translate("MainWindow", "Suspendidos: -"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

